Repository T3M4/GroupOrder, pull requests merged in 2020-01, with the labels that each got.

#129 72 feat/user can confirm his decision to form group order
  Extention/menu.js
  Extention/styles.css
  app.pid
  src/main/java/org/interlink/grouporder/core/data/DataStorage.java
  src/main/java/org/interlink/grouporder/core/entity/GroupOrder.java
  src/main/java/org/interlink/grouporder/misteram/MisterAmMapper.java
  src/main/java/org/interlink/grouporder/misteram/controllers/OrderController.java
Labels: enhancement, front-end

#133 68 feat/user can see group order
  Extention/background.js
  Extention/connect.html
  Extention/connect.js
  Extention/content.js
  Extention/home.png
  Extention/manifest.json
  Extention/menu.html
  Extention/menu.js
  Extention/newOrder.html
  Extention/newOrder.js
  Extention/popUp.html
  Extention/popUp.js
  Extention/styles.css
  Extention/transfer.html
  build.gradle
  src/main/java/org/interlink/grouporder/core/data/DataStorage.java
  src/main/java/org/interlink/grouporder/core/entity/GroupOrder.java
  src/main/java/org/interlink/grouporder/core/entity/MemberOrder.java
  src/main/java/org/interlink/grouporder/core/entity/Product.java
  src/main/java/org/interlink/grouporder/core/entity/view/GroupOrderView.java
  src/main/java/org/interlink/grouporder/core/exceptions/BadRequestException.java
  src/main/java/org/interlink/grouporder/core/exceptions/ForbiddenException.java
  src/main/java/org/interlink/grouporder/core/exceptions/UnprocessableEntityException.java
  src/main/java/org/interlink/grouporder/core/handler/ExceptionsHandler.java
  src/main/java/org/interlink/grouporder/core/handler/ExceptionsTypes.java
  src/main/java/org/interlink/grouporder/core/utils/OrderCodeGenerator.java
  src/main/java/org/interlink/grouporder/entity/Order.java
  src/main/java/org/interlink/grouporder/entity/OrderMember.java
  src/main/java/org/interlink/grouporder/entity/Product.java
  src/main/java/org/interlink/grouporder/misteram/MisterAmMapper.java
  src/main/java/org/interlink/grouporder/misteram/controllers/OrderController.java
  src/main/java/org/interlink/grouporder/misteram/entity/Item.java
  src/main/java/org/interlink/grouporder/misteram/entity/Order.java
  src/main/java/org/interlink/grouporder/order/OrderController.java
  src/main/java/org/interlink/grouporder/utils/JsonDecoder.java
  src/main/java/org/interlink/grouporder/utils/JsonEncoder.java
  src/main/java/org/interlink/grouporder/utils/OrderStorage.java
Labels: back-end, enhancement

#137 user can see loading screen while requests send to misteram
  Extention/connect.html
  Extention/menu.html
  Extention/menu.js
  Extention/newOrder.html
  Extention/popUp.html
  Extention/styles.css
Labels: enhancement, front-end

#136 #113 ProductsCounter: add: function of counting products
  src/main/java/org/interlink/grouporder/core/entity/Product.java
  src/main/java/org/interlink/grouporder/core/utils/ProductsCounter.java
Labels: back-end, enhancement

#167 166 feat/mapper for split bill
  src/main/java/org/interlink/grouporder/splitbill/entity/Item.java
  src/main/java/org/interlink/grouporder/splitbill/entity/OrderCheck.java
  src/main/java/org/interlink/grouporder/splitbill/entity/SplitBillMapper.java
Labels: back-end, enhancement

#182 #172 fix: update unit tests
  src/main/java/org/interlink/grouporder/core/data/DataStorage.java
  src/main/java/org/interlink/grouporder/core/entity/GroupOrder.java
  src/main/java/org/interlink/grouporder/core/exceptions/BadRequestException.java
  src/main/java/org/interlink/grouporder/core/exceptions/ForbiddenException.java
  src/main/java/org/interlink/grouporder/core/exceptions/UnprocessableEntityException.java
  src/test/java/org/interlink/grouporder/core/data/DataStorageTest.java
  src/test/java/org/interlink/grouporder/core/entity/GroupOrderTest.java
  src/test/java/org/interlink/grouporder/core/handler/ExceptionsHandlerTest.java
  src/test/java/org/interlink/grouporder/core/utils/ProductsCounterTest.java
Labels: back-end, bug

#187 #151 fix: user can't connect to the old group Order. Formed key is Unique
  src/main/java/org/interlink/grouporder/core/entity/GroupOrder.java
  src/main/java/org/interlink/grouporder/core/utils/OrderCodeGenerator.java
  src/main/java/org/interlink/grouporder/misteram/controllers/OrderController.java
Labels: back-end, bug

#189 #157 fix: restaurant in GroupOrder and restaurant in MemberOrder comp…
  src/main/java/org/interlink/grouporder/core/entity/GroupOrder.java
  src/main/java/org/interlink/grouporder/core/utils/OrderCodeGenerator.java
  src/test/java/org/interlink/grouporder/core/entity/GroupOrderTest.java
Labels: back-end, bug

#194 #188_issue MemberOrder: add: added new field to member of group order…
  src/main/java/org/interlink/grouporder/core/entity/MemberOrder.java
  src/main/java/org/interlink/grouporder/misteram/MisterAmMapper.java
  src/main/java/org/interlink/grouporder/misteram/entity/MemberOrderDTO.java
  src/main/java/org/interlink/grouporder/splitbill/SplitBillMapper.java
  src/main/java/org/interlink/grouporder/splitbill/entity/MemberDTO.java
Labels: back-end, enhancement

#196 #195 refactor: refactor unit tests and replaced list to map
  src/main/java/org/interlink/grouporder/core/data/DataStorage.java
  src/main/java/org/interlink/grouporder/core/entity/GroupOrder.java
  src/main/java/org/interlink/grouporder/core/entity/MemberOrder.java
  src/main/java/org/interlink/grouporder/core/utils/OrderCodeGenerator.java
  src/main/java/org/interlink/grouporder/misteram/controllers/OrderController.java
  src/main/java/org/interlink/grouporder/splitbill/SplitBillMapper.java
  src/test/java/org/interlink/grouporder/core/data/DataStorageTest.java
  src/test/java/org/interlink/grouporder/core/entity/GroupOrderTest.java
Labels: back-end, enhancement

#199 190 feat/user can remove himself from order
  src/main/java/org/interlink/grouporder/core/entity/GroupOrder.java
  src/main/java/org/interlink/grouporder/misteram/controllers/OrderController.java
  src/test/java/org/interlink/grouporder/core/entity/GroupOrderTest.java
Labels: back-end, enhancement
